"""Add country column to Match and Standing tables

Revision ID: 7403605e933a
Revises: 
Create Date: 2026-04-21 01:35:51.925082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7403605e933a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('matches', 'match_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('matches', 'league_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('matches', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('matches', 'venue_name')
    op.drop_column('matches', 'referee')
    op.drop_column('matches', 'weather')
    op.drop_column('matches', 'odds_draw')
    op.drop_column('matches', 'odds_home')
    op.drop_column('matches', 'lineup_data')
    op.drop_column('matches', 'venue_city')
    op.drop_column('matches', 'h2h_data')
    op.drop_column('matches', 'odds_away')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('odds_away', mysql.FLOAT(), nullable=True))
    op.add_column('matches', sa.Column('h2h_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('matches', sa.Column('venue_city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('matches', sa.Column('lineup_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('matches', sa.Column('odds_home', mysql.FLOAT(), nullable=True))
    op.add_column('matches', sa.Column('odds_draw', mysql.FLOAT(), nullable=True))
    op.add_column('matches', sa.Column('weather', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('matches', sa.Column('referee', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('matches', sa.Column('venue_name', mysql.VARCHAR(length=100), nullable=True))
    op.alter_column('matches', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('matches', 'league_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('matches', 'match_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('matches', 'created_at')
    op.drop_column('matches', 'country')
    # ### end Alembic commands ###
