"""add_preview_fields_to_matches

Revision ID: b12ca4a806c7
Revises: 7403605e933a
Create Date: 2026-04-25 18:39:34.649195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12ca4a806c7'
down_revision: Union[str, Sequence[str], None] = '7403605e933a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('referee', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('venue_name', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('venue_city', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('league_round', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'league_round')
    op.drop_column('matches', 'venue_city')
    op.drop_column('matches', 'venue_name')
    op.drop_column('matches', 'referee')
    # ### end Alembic commands ###
